color: red
fieldLayouts:
  180c1d19-c462-41dd-8a5d-ffcda2b2674d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e7ca0e8-d2aa-4bc4-861e-a4c121727b28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c075c4-e914-4ea5-b975-317ccc5e84c2 # Banner image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 681008cd-8ee3-4a2f-977a-99d4ffe5a0af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a28d632-b3db-4a2f-813b-6c5f8aa4de42 # Afbeeldingen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dda1d9d-9484-4d6c-9458-725b9842af10
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 14c4455e-ca6d-431a-be67-274de1ee715c
        userCondition: null
handle: galerij
hasTitleField: true
icon: files
name: Galerij
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
