color: violet
fieldLayouts:
  0a152b0d-d094-401f-927a-6d9775b3bdca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aed9cbe0-21b3-427a-b62d-fb1ce1fc49bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 548882c7-bab2-46dd-a368-a9fe271ae2d5 # Geschiedenis foto
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea456f26-0fa9-41e2-bd59-5e306119b774
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1cd5fb98-c27f-4926-96b3-eba8227130b9 # Geschiedenis Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f473574-020f-4604-a894-c1b180fc74e0
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 2b36b9c0-e244-459d-99ab-3fbe2340803a
        userCondition: null
handle: geschiedenissectie
hasTitleField: true
icon: timeline
name: 'Geschiedenis sectie'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
