color: teal
fieldLayouts:
  ed314365-c003-4a9b-97b6-919fc4a56609:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff3402c8-41e0-4953-8a5f-8d6fac9d669b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3dd5823f-33e4-46ce-854a-fbe4ee567aa9 # Naam
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54d26c36-7c5e-4376-88a7-971a5c7cc738
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab263836-9337-46e0-8d10-e16fcec9d30f # Periode
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63c4b29f-fa3d-4c34-9a1e-175b97b08cfb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a138341f-504d-4ea1-bdab-095eb8cf3d0e # Dirigent image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94c9907a-bdaa-44dd-8ef6-8fe59d450734
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: c5537eb1-90c5-4832-ae5d-97f75c50605f
        userCondition: null
handle: ouddirigent
hasTitleField: false
icon: user
name: 'oud dirigent'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{naam}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
