color: red
fieldLayouts:
  efc6165d-9c77-4250-8e41-f3c125beee96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa85e048-1bb8-4105-b95f-f594ad1c684e
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 49e2ce6e-8756-440d-ad63-b23c030d83e0
        userCondition: null
handle: paginas
hasTitleField: true
icon: files
name: Paginas
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
