color: null
fieldLayouts:
  2add22b2-b88c-4ad6-b702-74967ac78b85:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7cf0c3df-708b-457c-bb13-c18af3701091
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5676078-a97f-487b-a3a1-b6e21e63d9f9 # Social icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adeecaba-f9fc-4299-809d-d62e22455c10
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6db965dc-bfb5-47a1-b3ad-e70d24d5cf62 # Linken naar
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08162a1d-e336-42fa-a627-daa700f21d35
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: d5048a93-1497-4b40-b594-1b60334ea1df
        userCondition: null
handle: socials
hasTitleField: true
icon: hashtag
name: Socials
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
