defaultPlacement: end
fieldLayouts:
  661d71f5-53ca-4150-ad80-2e93d276f57e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 9c679ba7-716b-4aa9-bc1b-abd5db315d64
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 76634625-6216-4226-8bbe-713444862408
        userCondition: null
handle: bezetting
name: Bezetting
siteSettings:
  837e69ec-52da-4cbb-9013-dd888efcd6e3: # Koninklijke Fanfare <<Eendracht Maakt Macht>> Lot
    hasUrls: true
    template: null
    uriFormat: 'bezetting/{slug}'
structure:
  maxLevels: null
  uid: 72c5d24e-a806-41c6-a067-e9c03e92e490
