altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  552df865-b3e6-4220-b56c-e6d071766abe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: aa8a9a4b-0ba7-47e4-8a6e-e88e678f65b2
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 784f91a8-2670-437c-830b-8275d33d8295
        userCondition: null
fs: uploads
handle: images
name: images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
