columnSuffix: null
handle: geschiedenissecties
instructions: null
name: 'Geschiedenis secties'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - a3123bf3-4f17-4255-8e27-f57d79afc73a # Geschiedenis sectie
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
