defaultPlacement: end
enableVersioning: true
entryTypes:
  - c76b8343-2746-463c-9d98-e38c51c2b9f7 # Logo
handle: logo
maxAuthors: 1
name: Logo
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  837e69ec-52da-4cbb-9013-dd888efcd6e3: # Koninklijke Fanfare <<Eendracht Maakt Macht>> Lot
    enabledByDefault: true
    hasUrls: true
    template: logo/_entry
    uriFormat: logo
type: single
